export enum ComponentTypes {
  Anvil = 'anvil',
  Desk = 'desk',
  Position = 'position',
  ItemHolder = 'item-holder',
  Sprite = 'sprite',
  Player = 'player',
  Interaction = 'interaction',
  Label = 'label',
  Pickable = 'pickable',
  Physics = 'physics',
  Spawner = 'spawner',
  Funnel = 'funnel',
  Furnace = 'furnace',
  Steel = 'steel',
  Transformer = 'transformer',
  Sharpener = 'sharpener',
}
